# Generated by Django 3.1.4 on 2020-12-15 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cycleshareapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='rider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cycleshareapi.rider'),
            preserve_default=False,
        ),
    ]
